// commands ref: https://github.com/sparksuite/simplemde-markdown-editor/blob/master/src/js/simplemde.js#L1882
export enum MarkdownCommand {
  ToggleBold = 'toggleBold',
  ToggleItalic = 'toggleItalic',
  ToggleStrikethrough = 'toggleStrikethrough',
  ToggleBlockquote = 'toggleBlockquote',
  ToggleHeadingSmaller = 'toggleHeadingSmaller',
  ToggleHeadingBigger = 'toggleHeadingBigger',
  ToggleHeading1 = 'toggleHeading1',
  ToggleHeading2 = 'toggleHeading2',
  ToggleHeading3 = 'toggleHeading3',
  ToggleCodeBlock = 'toggleCodeBlock',
  ToggleUnorderedList = 'toggleUnorderedList',
  ToggleOrderedList = 'toggleOrderedList',
  CleanBlock = 'cleanBlock',
  DrawLink = 'drawLink',
  DrawImage = 'drawImage',
  DrawTable = 'drawTable',
  DrawHorizontalRule = 'drawHorizontalRule',
  Undo = 'undo',
  Redo = 'redo',
  TogglePreview = 'togglePreview',
  ToggleSideBySide = 'toggleSideBySide',
  ToggleFullScreen = 'toggleFullScreen'
}
